# Generated by Django 5.0.3 on 2024-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'client'), ('ADMIN', 'admin'), ('TRAINER', 'trainer')], max_length=30, null=True),
        ),
    ]
