# Generated by Django 5.0.3 on 2024-04-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userprofile_status_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'client'), ('TRAINER', 'trainer'), ('ADMIN', 'admin')], max_length=30, null=True),
        ),
    ]
