# Generated by Django 5.0.3 on 2024-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_otp_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('TRAINER', 'trainer'), ('CLIENT', 'client'), ('ADMIN', 'admin')], max_length=30, null=True),
        ),
    ]
