# Generated by Django 5.0.3 on 2024-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userprofile_status_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('TRAINER', 'trainer'), ('CLIENT', 'client')], max_length=30, null=True),
        ),
    ]
