# Generated by Django 5.0.3 on 2024-04-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscriptionplan',
            field=models.CharField(blank=True, choices=[('PREMIUM', 'premium'), ('ORDINARY', 'ordinary'), ('STANDARD', 'standard')], default='ORDINARY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('TRAINER', 'trainer'), ('CLIENT', 'client'), ('ADMIN', 'admin')], max_length=30, null=True),
        ),
    ]
