# Generated by Django 5.0.3 on 2024-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userprofile_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscriptionplan',
            field=models.CharField(blank=True, choices=[('ORDINARY', 'ordinary'), ('STANDARD', 'standard'), ('PREMIUM', 'premium')], default='ORDINARY', max_length=100, null=True),
        ),
    ]
