# Generated by Django 5.0.3 on 2024-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_userprofile_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscriptionplan',
            field=models.CharField(blank=True, choices=[('PREMIUM', 'premium'), ('STANDARD', 'standard'), ('ORDINARY', 'ordinary')], default='ORDINARY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('CLIENT', 'client'), ('TRAINER', 'trainer')], max_length=30, null=True),
        ),
    ]
