# Generated by Django 5.0.3 on 2024-04-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscriptionplan',
            field=models.CharField(blank=True, choices=[('PREMIUM', 'premium'), ('ORDINARY', 'ordinary'), ('STANDARD', 'standard')], default='ORDINARY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('CLIENT', 'client'), ('TRAINER', 'trainer')], max_length=30, null=True),
        ),
    ]
