# Generated by Django 5.0.3 on 2024-04-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_userprofile_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscriptionplan',
            field=models.CharField(blank=True, choices=[('ORDINARY', 'ordinary'), ('PREMIUM', 'premium'), ('STANDARD', 'standard')], default='ORDINARY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'client'), ('TRAINER', 'trainer'), ('ADMIN', 'admin')], max_length=30, null=True),
        ),
    ]
