# Generated by Django 5.0.3 on 2024-04-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_rename_like_videolike_likestatus_alter_bank_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='status',
            field=models.CharField(blank=True, choices=[('DEACTIVE', 'Deactive'), ('ACTIVE', 'Active')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='videolike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videolike',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='videolike',
            name='status',
            field=models.CharField(blank=True, choices=[('DEACTIVE', 'Deactive'), ('ACTIVE', 'Active')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='videolike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
