# Generated by Django 5.0.3 on 2024-04-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_alter_bank_status_alter_chat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolike',
            name='likestatus',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
