# Generated by Django 5.0.3 on 2024-04-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_videolike_likestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolike',
            name='likestatus',
        ),
    ]
