# Generated by Django 5.0.3 on 2024-04-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_remove_videolike_likestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='FROM_ID',
            new_name='from_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='TO_ID',
            new_name='to_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='date',
        ),
    ]
