# Generated by Django 5.0.3 on 2024-04-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_rename_from_id_chat_from_id_rename_to_id_chat_to_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
    ]
