# Generated by Django 5.0.3 on 2024-04-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
