# Generated by Django 5.0.3 on 2024-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_rename_user_diet_trainer_alter_posture_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainerrating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
