# Generated by Django 5.0.3 on 2024-04-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_alter_posture_status_alter_trainer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posture',
            old_name='video',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='posture',
            name='likes',
        ),
        migrations.AddField(
            model_name='posture',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
