# Generated by Django 5.0.3 on 2024-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0019_alter_challenges_status_alter_diet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posture',
            name='likes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posture',
            name='overallrating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
