# Generated by Django 5.0.3 on 2024-04-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0025_alter_challenges_status_alter_diet_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posture',
            name='thumbnail',
        ),
    ]
