# Generated by Django 5.0.3 on 2024-04-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0026_remove_posture_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
