# Generated by Django 5.0.3 on 2024-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0027_alter_posture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='trainerposture/'),
        ),
    ]
