# Generated by Django 5.0.3 on 2024-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminfitness', '0009_alter_category_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionname', models.CharField(blank=True, max_length=100, null=True)),
                ('monthlyprice', models.CharField(blank=True, max_length=100, null=True)),
                ('workoutvideoes', models.BooleanField(default=True)),
                ('dietplans', models.BooleanField(default=True)),
                ('workoutchallenges', models.BooleanField(default=True)),
                ('chatsupport', models.BooleanField(default=True)),
                ('physiotherapy', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('DEACTIVE', 'Deactive'), ('ACTIVE', 'Active')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('DEACTIVE', 'Deactive'), ('ACTIVE', 'Active')], max_length=20, null=True),
        ),
    ]
